### PR TITLE
Add support for python 3.7, remove support for python 3.4

### PR DESCRIPTION
**Pull request by asherf**
Python 3.4 is EOL
https://devguide.python.org/devcycle/#end-of-life-branches

### CODE REVIEW

**Comment by rhgrant10** [comment]
Hey @ashref thanks for this! Looks good. Do we know why using the xenial distro is required?

**Comment by asherf** [comment]
https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
I think the ubuntu version travis defaults to doesn't have python 3.7.

**Comment by rhgrant10** [comment]
Ah gotcha. Yeah I'll merge this soon. Thanks again!

**Comment by rhgrant10** [comment]
@asherf available in [v0.2.0 on PyPI](https://pypi.org/project/ndjson/0.2.0/) 👍

**Pull request merged**
